import React from "react";
import Link from "next/link";
import Head from "next/head";

export default function AboutPage() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-blue-50 via-slate-50 to-indigo-100">
      <Head>
        <title>About & Credits | AI Tech Blog</title>
        <meta name="description" content="Learn about our mission, how we credit Reddit users and websites, and our commitment to AI transparency at AI Tech Blog." />
        <meta property="og:title" content="About & Credits | AI Tech Blog" />
        <meta property="og:description" content="Learn about our mission, how we credit Reddit users and websites, and our commitment to AI transparency at AI Tech Blog." />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://yourdomain.com/about" />
        <meta property="og:site_name" content="AI Tech Blog" />
        <meta property="og:image" content="/screenshot.png" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="About & Credits | AI Tech Blog" />
        <meta name="twitter:description" content="Learn about our mission, how we credit Reddit users and websites, and our commitment to AI transparency at AI Tech Blog." />
        <meta name="twitter:image" content="/screenshot.png" />
      </Head>
      {/* Hero Header */}
      <section className="w-full bg-gradient-to-r from-blue-600 to-purple-600 py-16 px-4 text-center text-white shadow-lg">
        <div className="max-w-2xl mx-auto">
          <div className="flex justify-center mb-6">
            <span className="inline-flex items-center justify-center h-20 w-20 rounded-full bg-white/20">
              <svg className="h-12 w-12 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M12 20.5C7.305 20.5 3.5 16.695 3.5 12S7.305 3.5 12 3.5 20.5 7.305 20.5 12 16.695 20.5 12 20.5z" /></svg>
            </span>
          </div>
          <h1 className="text-4xl md:text-5xl font-extrabold mb-4 drop-shadow-lg">About & Credits</h1>
          <p className="text-lg md:text-xl font-medium mb-6 max-w-xl mx-auto opacity-90">
            AI Tech Blog is devoted to sharing the best in tech, cybersecurity, and AI—generated by AI, inspired by the web, and always giving credit where it’s due.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center mt-8">
            <Link href="/" className="bg-white/90 text-blue-700 font-semibold px-6 py-2 rounded-full shadow hover:bg-white">Back to Home</Link>
            <Link href="/contact" className="bg-blue-700 text-white font-semibold px-6 py-2 rounded-full shadow hover:bg-blue-800">Contact Us</Link>
          </div>
        </div>
      </section>
      {/* Main Content */}
      <section className="max-w-2xl mx-auto bg-white/95 rounded-3xl shadow-xl ring-1 ring-gray-200 p-8 md:p-14 lg:p-16 mt-[-4rem] relative z-10">
        <h2 className="text-2xl font-bold mb-4 text-blue-700">Our Mission</h2>
        <p className="mb-8 text-gray-700 text-lg leading-relaxed">
          We use AI to generate blog posts from trending Reddit topics and web discussions, making tech news fun, accessible, and always up-to-date.
        </p>
        <h2 className="text-2xl font-bold mb-4 text-blue-700">Giving Credit</h2>
        <p className="mb-4 text-gray-700">
          We are grateful to Reddit users and websites whose insights inspire our content. We strive to:
        </p>
        <ul className="list-disc pl-6 mb-8 text-gray-700">
          <li>Credit original Reddit threads and users whenever possible</li>
          <li>Acknowledge the use of public web content as inspiration</li>
          <li>Respond promptly to any requests for credit, removal, or corrections</li>
        </ul>
        <h2 className="text-2xl font-bold mb-4 text-blue-700">AI Transparency</h2>
        <p className="mb-8 text-gray-700">
          All articles are written by AI, curated and edited for clarity and fun. We believe in transparency and want you to know exactly how our content is created.
        </p>
        <h2 className="text-2xl font-bold mb-4 text-blue-700">Explore More</h2>
        <ul className="list-disc pl-6 mb-8 text-blue-700">
          <li><Link href="/topics" className="hover:underline">Browse Topics</Link></li>
          <li><Link href="/newsletter" className="hover:underline">Subscribe to our Newsletter</Link></li>
          <li><Link href="/archive" className="hover:underline">View the Archive</Link></li>
        </ul>
        <h2 className="text-2xl font-bold mb-4 text-blue-700">Contact & Feedback</h2>
        <p className="mb-2 text-gray-700">
          Are you a Reddit user, website owner, or just a curious reader? Want to be credited, have your content removed, or just say hi?
        </p>
        <Link href="/contact" className="text-blue-600 hover:underline font-semibold">Contact us here</Link>.
        <p className="text-gray-400 text-xs mt-8">We’re here to have fun, learn, and share the best of the web—together.</p>
      </section>
    </main>
  );
} 