import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ 
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_SITE_URL && process.env.NEXT_PUBLIC_SITE_URL.trim() !== ''
      ? process.env.NEXT_PUBLIC_SITE_URL
      : 'http://localhost:3000'
  ),
  title: "AI Tech Blog - AI-Generated Tech, Cybersecurity & SaaS News",
  description: "Stay updated with the latest in tech, cybersecurity, AI, and SaaS. All blogs are generated by AI, inspired by trending Reddit topics, and illustrated with AI-generated images. We credit all sources and are transparent about our use of AI.",
  keywords: ["AI", "Technology", "Cybersecurity", "SaaS", "Blog", "Tech News", "Reddit", "Artificial Intelligence"],
  authors: [{ name: "AI Tech Blog" }],
  openGraph: {
    title: "AI Tech Blog - AI-Generated Tech, Cybersecurity & SaaS News",
    description: "Stay updated with the latest in tech, cybersecurity, AI, and SaaS. All blogs are generated by AI, inspired by trending Reddit topics, and illustrated with AI-generated images.",
    type: "website",
    url: "https://yourdomain.com/",
    siteName: "AI Tech Blog",
    images: [
      {
        url: "/screenshot.png",
        width: 1200,
        height: 630,
        alt: "AI Tech Blog Screenshot"
      }
    ]
  },
  twitter: {
    card: "summary_large_image",
    title: "AI Tech Blog - AI-Generated Tech, Cybersecurity & SaaS News",
    description: "Stay updated with the latest in tech, cybersecurity, AI, and SaaS. All blogs are generated by AI, inspired by trending Reddit topics, and illustrated with AI-generated images.",
    images: ["/screenshot.png"]
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`scroll-smooth ${inter.variable}`}>
      <head>
        {/* SEO Meta Tags */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="robots" content="index, follow" />
        <meta name="theme-color" content="#2563eb" />
        {/* Open Graph & Twitter tags are handled by next/metadata */}
      </head>
      <body className="antialiased font-sans">
        {children}
      </body>
    </html>
  );
}
